projects:
  app:
    schemaPath: ./api/src/schema.graphql
    extensions:
      endpoints:
        default: ${env:GRAPHQL_ENDPOINT}
  hasura:
    extensions:
      endpoints:
        default: ${env:HASURA_ENDPOINT}